broker:
    host: "localhost"
    port: 1883
    user: ""
    password: ""

topics:
    - In: "A1"
      Out: "Out1"
      Op: "100*In"
    - In: "A2"
      Op: "1 + In"
      Out: "Out2"
    - In: "A3"
      Out: "Out3"
    - In: "A1"
      Out: "Out3"
    - In: "A1"
      Out: "Out3"
      Op: "Out = In + 1"
