broker:
    host: "localhost"
    port: 1883
    user: ""
    password: ""

topics:
  # the following data could be used for test purposes
    # - In: "A1"
    #   Out: "Out1"
    #   Op: "10*In"
    # - In: "A1"
    #   Out: "Out1"
    #   Op: "10*In + 1"  
    # - In: "A1"
    #   Out: "Out4"
    #   Op: "In/3"     
    # - In: "A2"
    #   Op: "1 + In"
    #   Out: "Out2"
    # - In: "A3"
    #   Out: "Out3"
    # - In: "A1"
    #   Out: "Out3"
