
SYSTEM_PATH = "/etc/"

COMMON_PATH = "topicator/"

DDG_STATE_FILE = COMMON_PATH + "ddg_states.json"
IDD_STATE_FILE = COMMON_PATH + "idd_states.json"

CONFIG_FILE = "config.yaml"

CONFIG_FILE_SYSTEM_FULL_PATH = SYSTEM_PATH + COMMON_PATH + CONFIG_FILE
